
#define INTERFACE_OPENAUDRESFILTER "Audio Volume Documents (*.AUD)\0*.aud\0\0"  
#define INTERFACE_OPENMAPFILTER "Audio Map Documents (*.map)\0*.map\0Volume Map Documents (*.map)\0*.map\0\0"  
#define INTERFACE_SAVEMAPFILTER "Audio Map Documents (*.map)\0*.map\0\0"  
#define INTERFACE_OPENFILEFILTER "Message Documents (*.msg)\0*.msg\0All the types  (*.*)\0*.*\0\0"  
#define INTERFACE_SAVEFILEFILTER "Sierra Message Documents (*.msg)\0*.msg\0TraduSCI2 Message Documents (*.msg)\0*.msg\0\0"  
#define INTERFACE_SAVEMSGFILEFILTER "Message Documents (*.msg)\0*.msg\0\0"  
#define INTERFACE_EXPORTTEXTFILTER "Text Documents (*.txt)\0*.txt\0All the types (*.*)\0*.*\0\0"  
#define INTERFACE_LOADHEAPFILEFILTER "Heap Documents (*.hep)\0*.hep\0Volume Map Documents (*.map)\0*.map\0\0"  
#define INTERFACE_GOBUTTON "Go"  
#define INTERFACE_FINDBUTTON "Search"  
#define INTERFACE_REPLACEBUTTON "Replace"  
#define INTERFACE_CASESENSITIVE "with ABC =/= abc"  
#define INTERFACE_ORIGINALBUTTON "in Messages"  
#define INTERFACE_TRANSLATIONBUTTON "in Translations"  
#define INTERFACE_ORIGINAL "M\nE\nS\nS"  
#define INTERFACE_TRANSLATION "T\nR\nA\nN"  
#define INTERFACE_COMMENTS "N\nO\nT\nE"  
#define INTERFACE_ITEMCOUNT " sentences"  
#define INTERFACE_NOFILELOADED "No Message file loaded"  
#define INTERFACE_FILECOMPARETITLE "Select a file to compare"  
#define INTERFACE_SEARCHTITLE "Search Status"  
#define INTERFACE_ENDOFFILESSTR "Seeking is returned on the first file from which it started."  
#define INTERFACE_INVALIDSEARCHHANDLE "Seeking cannot be continued, the file could have been moved or removed."  
#define INTERFACE_SELECTOP "Choose an operation: "  
#define INTERFACE_LABEL "Label"  
#define INTERFACE_CLONEOF "Clone of"  
#define INTERFACE_SEARCH "in"  
#define INTERFACE_INDEX "Index"  
#define INTERFACE_NOUN "Noun"  
#define INTERFACE_VERB "Verb"  
#define INTERFACE_CASE "Case"  
#define INTERFACE_SEQUENCE "Sequence"  
#define INTERFACE_TALKER "Talker"  
#define INTERFACE_MESSAGE "Message"  
#define INTERFACE_MTRANSLATION "Translation"  
#define INTERFACE_COMMENT "Notes"  
#define INTERFACE_UNCLONINGTITLE "Cloning"  
#define INTERFACE_PROPERTIESTITLE "Properties"  
#define INTERFACE_PROPERTIESFORMATSTRING "\nSCI Version: %s                   \nFile Format: %s\nSentences: %d\nUnknown value: %d\nNotes: %s\nMap File: %s\n"  
#define INTERFACE_GENERICLABEL "<generic>"  
#define INTERFACE_GENERICFLABEL "<generic>"  
  
#define BUTTON_NEXTFILE "Next file"  
#define BUTTON_STOPSEARCH "Stop"  
#define BUTTON_FIRSTSTRING "First sentence"  
  
#define BUTTON_CANCEL "Cancel"  
#define BUTTON_SELECTAUDMAP "Modify MAP"  
#define BUTTON_JUSTUNCLONE "Just UnClone"  
  
#define BUTTON_CLOSE "Close"  
#define BUTTON_LOADMSG "Load MSG"  
#define BUTTON_LOADRES "Open Volume"  
#define BUTTON_MANUAL "Manual"  
  
#define EXPORT_INFO "\n\n--Attention: The first part of this file lists the sentences translated for using with the Orthographic check. If carriage return are added in that section, these will be inserted in the sentences. Also, do not modify the numbers that identify the sentences. \nData starting from this point are not sensitive and can be removed if not necessary.--\n\n\n"  
#define EXPORT_ITEM "Sentence %u:\n%s\n\n"  
#define EXPORT_ENDSECTION "\n\n---- End of the section ----\n"  
#define EXPORT_COPYRIGHT "This file has been produced by SCIaMano 1.3.1 by Enrico Rolfi.\n\n\n"  
#define EXPORT_FILEPATH "Path: %s\n"  
#define EXPORT_FORMAT "Format: %s\n"  
#define EXPORT_VERSION "Version: %s\n"  
#define EXPORT_ITEMCOUNT "Number of Sentences: %u\n"  
#define EXPORT_COMMENTS "Comments available: %s\n"  
#define EXPORT_YES "Yes"  
#define EXPORT_NO "No"  
#define EXPORT_ITEM2 "- Sentence %u - \n%s\n\n"  
#define EXPORT_TRANSLATION "- Translation - \n%s\n\n"  
#define EXPORT_COMMENTITEM " - Note - \n%s\n\n"  
#define EXPORT_ENDOFFILE "\n\n---- End of file ----\n\n"  
  
#define EXPORT_DIFFTITLE "Differences between the current file and a second file\n\nFile 1 - %s\nFile 2 - %s\n\n"  
#define EXPORT_MAPTITLE "List of the sentences not found in the selected MAP!\n\n"  
  
#define IMPORT_CANTFINDLABEL "Can't find the sentence %s in the text file, because there is %s in its place."  
  
#define ERR_TITLE "Error"  
#define ERR_CANTLOADFILE "Cannot load the file because of an error."  
#define ERR_FILEMOVED "The file doesn't exist, it has been moved or removed."  
#define ERR_CANTSAVECHANGES "Cannot save the changes to the file. Please try to save to a new file."  
#define ERR_CANTSAVE "Cannot save the new file because of an error."  
#define ERR_CANTEXPORTTEXT "Cannot export the sentences because of an error."  
#define ERR_NEWERFILEVERSION "This file has been created with a more recent version of SCIaMano and cannot be used."  
#define ERR_STRITEM1 "A problem of memory has occurred in strItem->setString(tempStr) of the format Sierra."  
#define ERR_STRITEM2 "A problem of memory has occurred in strItem->setString(tempStr2) of the format TraduSCI."  
#define ERR_STRITEM3 "A problem of memory has occurred in strItem->setTranString(tempStr) of the format TraduSCI."  
#define ERR_STRITEM4 "A problem of memory has occurred in strItem->setString(tempStr) of the format TraduSCI."  
#define ERR_COMITEM "A problem of memory has occurred in comItem->setString(tempStr). "  
#define ERR_UNKNOWNGAME "The selected file seems to belong to a game that I do not own. Please, contact me so I can add the support for it. (VersionTag = 0x%X) "  
#define ERR_MESSAGEFROMAUTHOR "Message from Enrico Rolfi (Endroz) "  
#define ERR_FIELD1 "Cannot create the field of the sentences."  
#define ERR_FIELD2 "Cannot create the field of the translations."  
#define ERR_FIELD3 "Cannot create the field of the comments."  
#define ERR_FIELD4 "Cannot create the Index field."  
#define ERR_FIELD5 "Cannot create the Search field."  
#define ERR_FIELD6 "Cannot create the Replace field."  
#define ERR_DIFFIMPFILE "The selected file has a different number of sentences and cannot be Imported."  
#define ERR_DIFFCMPFILE "The selected file has a different number of sentences and cannot be compared."  
#define ERR_CANTCMPSAMEFILE "The selected file is the same file you're asking to compare to!"  
#define ERR_CANTALLOCSTRING "A problem of memory has occurred. The translated sentence has not been saved."  
#define ERR_CANTLOADHEAPFILE "Error in the loading of the Heap file!"  
#define ERR_CANTLOADDLL "Couldn't load SCIdump.dll! This program will crash if you will try to load a Volume file."
#define WARN_ATTENTION "Attention!"  
#define WARN_SIERRAFORMAT "The file is in Sierra format, so you can save only the translated sentences in the place of the original ones. Also it doesn't support the special data of TraduSCI (like MAP and labels). \nWould you like to convert it in TraduSCI format so to preserve both versions of the sentences (and the special data)?"  
#define WARN_OLDFORMAT "This file is in an old TraduSCI format, saving the changes will automatically converted it in TraduSCI2 format and you won't be able to used it in older versions of the program. Continue anyway? "  
#define WARN_UNSAVEDCHANGES "Your changes to the current file have not been saved. Do you want to save before opening another file? "  
#define WARN_QUITONUNSAVED "Your changes to the current file have not been saved. Do you want to save before closing SCIaMano? "  
  
#define WARN_TEMPORARYFILEEXISTS "A temporary file related to a previous session (or a still in progress session) has been found. Would you like to load this temporary file instead?"    
  
#define WARN_ENDOFFILEDURINGSEARCH "End of file. \n\nYou can restart from the first sentence or continue to the next file."  
  
#define WARN_ENDTAGNAMESNOTFOUND "There is a problem with this file. The end of the block of the labels has not been recognized! Proceed with caution."  
#define WARN_ENDTAGMAPSNOTFOUND "There is a problem with this file. The end of the block of the Audio MAP has not been recognized! Proceed with caution."  
  

#define MENU_MESSAGE "&Messages"  
#define MENU_LOAD "&Open... \tCtrl+O"  
#define MENU_OPENVOL "&Load from Volume... "  
#define MENU_SAVE "&Save\tCtrl+S"  
#define MENU_SAVEAS "S&ave as... "  
  
#define MENU_IMPORT "&Import from text file... "  
#define MENU_EXPORT "&Export on text file... "  
#define MENU_ABOUT "&About... "  
#define MENU_QUIT "&Quit\tCtrl+Q"  
#define MENU_PROPERTIES "&Properties... "    
#define MENU_CLONE "Cloning of the current sentence... "  
  
#define MENU_NOUNSHEAP "Import Noun names from Heap file... "  
#define MENU_LOADLABELSTXT "Import from text file... "  
#define MENU_EXPORTLABELSTOTXT "Export on text file"  
  
#define MENU_LABELS "Labels"  
  
#define MENU_STRING "&Sentences"  
#define MENU_FIRST "&First\tCtrl+Home"  
#define MENU_PREVIOUS "P&revious\tCtrl+Up Arrow"  
#define MENU_NEXT "&Next\tCtrl+Down Arrow"  
#define MENU_LAST "&Last\tCtrl+End"  
#define MENU_ENTER "&Go\tCtrl+Enter"  
  
#define MENU_FIND "&Search\tCtrl+F"  
#define MENU_REPLACE "&Replace\tCtrl+R"  
#define MENU_IMPORTFILE "I&mport from Message... "  
#define MENU_COMPAREFILE "&Compare with Message... "  
  
  
#define MENU_SHOWUNKBYTES "&Show special data"  
  
#define MENU_WORDL "Glossary"  
#define MENU_ADDTOWL "Add selection\tCtrl+A"  
#define MENU_DOWORDSLOOKUP "Check words\tCtrl+K"  
#define MENU_SHOWWL "Show Glossary"  
  
#define MENU_FONT "&Font size"  
#define MENU_FONT14 "14"  
#define MENU_FONT16 "16"  
#define MENU_FONT18 "18"  
#define MENU_FONT20 "20"  
#define MENU_FONT22 "22"  
#define MENU_FONT24 "24"  
#define MENU_FONT26 "26"  
  
#define MENU_NAVIGATION "&Navigation"  
  
  
#define MENU_GRAPH "Graphs"  
#define MENU_DRAWGF "Draw Graph\tCtrl+G"  
#define MENU_DRAWGFBW "Draw Graph without colors"  
  
#define MENU_OTHERGRAPH "... with different sorting"  
#define MENU_DRAWNOUNGF "Graph of the Nouns"  
#define MENU_DRAWCASEGF "Graph of the Cases"  
#define MENU_DRAWVERBGF "Graph of the Verbs"  
#define MENU_DRAWTALKERGF "Graph of the Talkers"  
#define MENU_DRAWINDEXGF "Graph of the Indexes"  
  
#define MENU_AUDIO "Audio"  
#define MENU_LOADMAP "Load MAP... "  
#define MENU_EXPORTMAP "Export current MAP... "  
#define MENU_VERIFYMAP "Verify messages in MAP... "  
  
#define MENU_PLAY "Play current sentence"  
#define MENU_LOADAUDRES "Locate 'RESOURCE.AUD'... "  
#define MENU_AUTOPLAY "Auto Play"  
  
#define MENU_NEXTCOMMENT "Go to the next Note\tCtrl+D"  
  
#define MENU_HELP "TraduSCI Manual... "   
  
#define WIN_FILEDESCRIPTION "Program to translate SCI1.1/SCI32 games.\0"  
#define WIN_LEGALCOPYRIGHT "\251 Enrico Rolfi (Endroz), 2003-2014.\0"  
#define WIN_LEGALTRADEMARKS "SCI (Sierra Creative Interpreter) is a trademark of Sierra On-line that holds copyrights on it. \0"  
#define WIN_FILEVERSION "1.3.1\0"  
#define WIN_PRODUCTVERSION "2.1\0"  
#define WIN_FILEVERSIONID 1,3,1,0  
#define INTERFACE_ABOUTBOX "This program is open source (GNU GPL license), and can be freely distributed and modified provided that it stays open source. The author declines from every responsibility on possible damages caused by its use.  SCI is a trademark of Sierra On-line."  
#define INTERFACE_ABOUTTITLE "\251 Enrico Rolfi (Endroz), 2003-2014\n\nUpdates on http://erolfi.wordpress.com\nFor problems, suggestions and other write to: \n erolfi@gmail.com\n\n"  
#define INTERFACE_VERSION "Version 1.3.1"  
  
#define MANUAL_PATH "Manual/instructions.html"  
          
  
#define GRAPH_CLONEOF "\\fn\nClone of Noun%d, Verb %d, Case %d"  
#define GRAPH_NOUN "Noun"  
#define GRAPH_VERB "Verb"  
#define GRAPH_CASE "Case"  
#define GRAPH_TALKER "Talker"  
#define GRAPH_CANTCREATEFILE "Cannot create the file of the graph (perhaps the disk is protected?). "  
  
#define MAPS_REPLACEEXISTING "This Message file already has an Audio MAP loaded, are you sure you want to replace it?"  
#define MAPS_MAPFILENOTFOUND "This MSG file needs a valid MAP file to be able to work in the game. Do you want to create it now (replacing any existing MAP file with the same name in this same directory)? "  
#define MAPS_WRONGENDOFMAPFILE "This MAP file doesn't have a recognized format therefore it is not possible to load it. \n(last element is not -1 as expected) "  
#define MAPS_WRONGMAPFILESIZE "Size of the MAP file is not correct therefore it is not possible to load it."  
#define MAPS_STRANGESCIPATCHINMAPFILE "The MAP file doesn't have a recognized format therefore it is not possible to load it. \n(there's no correct indicator of SCI PATCH at the beginning of the file) "  
#define MAPS_CANTACCESSMAPFILE "It's not possible to access the MAP file! "  
#define MAPS_ITEMALREADYEXISTS "It was not possible to insert the element in the MAP! An element already exists with the same label."  
#define MAPS_LISTERRORDURINGINSERT "It was not possible to insert the element in the MAP!\n(error during the insertion in the list)"  
#define MAPS_CANTFINDORIGINALTOCOPYFROM "It was not possible to insert the element in the MAP! The original sentence from which to copy the reference to the audio has not been found."  
#define MAPS_NOMAPINMEMORY "It is not present in memory a MAP structure on which to apply the requested changes!"  
#define MAPS_MAPCHECKFORMATSTRING "Index: %d - Noun: %d Verb: %d Case: %d Sequence: %d%s\n"  
#define MAPS_BUTITISACLONE " (but it is a Clone)"  
#define MAPS_CANTFINDENTRY "The reference to the audio has not been found in the MAP (it might be a clone)! "  
  
#define MAPS_WASNTREMOVEDMIGHTBEUSEFUL "The entry in the audio MAP has not been eliminated because it references to an existing sound sample, that could come in handy in case you will decide to UnClone this message in the future."  
#define MAPS_ENTRYREMOVED "The entry in the audio MAP has correctly been removed."  
#define MAPS_TITLE "Audio MAP"  
  
#define MAPS_NOTLOADED "not loaded"  
  
#define AUDIO_CANTFINDRESAUD "Can't find the volume RESOURCE.AUD! Please load it through the appropriate function in this very menu. If this has already been done, then please check that the MAP has not been moved or removed."  
#define AUDIO_NOTASOLFILE "The RESOURCE.AUD file or the audio MAP in use might be wrong. The actual address in the map Audio does not reference to any SOL audio file type!"  
#define AUDIO_MUSTLOADMAPFIRST "To be able to reproduce this sentence it is necessary to load the map Audio of this message file (for example: 100000.map). "  
   
#define CLONES_UNCLONEBTN "UnClone"  
#define CLONES_CLONEBTN "Clone"  
#define CLONES_SEQLABEL "SEQ"  
#define CLONES_HIERARCHICAL "Please remember that sentences belonging to lists or other interfaces might be handled in the scripts, and if uncloned could crash the game! (Note: uncloning this sentence will give you another clone, because the original sentence is a clone itself; therefore it will be necessary to repeat the operation of uncloning to get a modifiable sentence.) "   
#define CLONES_DUPLICATESEQ "This sentence is a clone of a whole sequence! Rather than uncloning the single sentence (thus getting only a copy of the first sentence of the sequence), would you like to copy that sequence, and relink this clone to this copy?"  
#define WARN_UNCLONINGAREYOUSURE "Please remember that sentences belonging to lists or other interfaces might be handled in the scripts, and if uncloned could crash the game!\n\nIn presence of Voices, it is required to modify the file of audio mapping (. MAP) too. You can do that by choosing the button right here (read the manual for further informations on clones): "   
#define CLONES_CANTUNCLONESEQ "Couldn't create a duplicate of the cloned sequence!"  
#define CLONES_UNCLONINGSUCCEDED "Operation of uncloning succeeded."  
#define CLONES_CANTCLONESEQINTERMEDIATE "An intermediary sentence of a sequence cannot be cloned!"  
#define CLONES_UNCLONEDSEQLABEL "UNCLONED SEQ"  
#define CLONES_LABELFORMAT "%sClone of Noun %d, Verb %d, Case %d"  
#define CLONES_CLONINGENTERINDEX "With this procedure, the current sentence will be turned into a clone!\n Enter the Index of the first message of the reference sequence from which to create the new clone: "  
#define CLONES_CLONINGREMARK "Note: if a reference to the current message exists in the MAP file, the procedure of cloning won't remove it (unless this is a previously uncloned message). Remember that, when displaying a clone, the game will always use the audio related to the original message."  
#define CLONES_CANTCLONEWRONGINDEX "The inserted index doesn't correspond to any message! "  
  
#define WORDS_WORDALREADYEXISTS "This word already exists in the glossary. Do you want to add a further definition? "  
#define WORDS_CANTACCESSWORDSFILE "Cannot open the glossary. Verify that the file \"wordlookup.txt\" is located in the same directory of the currently open MSG file."  
#define WORDS_NOSELECTIONTOADD "There is not any selection to add to the glossary!"  
#define WORDS_CANTCREATEREPORT "Cannot create the file containing the report! "  
  
#define WORDS_WFHEADERROW1 "# Glossary file for the common terms in the MSG\n#\n"  
#define WORDS_WFHEADERROW2 "# Syntax for every line of the file has to be like:\n#    <original word> = <translation1> | <translation2> |... \n#\n"  
#define WORDS_WFHEADERROW3 "# Words can contain spaces in between, so\n#  you can also save translations of whole sentences\n"  
#define WORDS_WFHEADERROW4 "# To insert comments, use the # character \n"  
  
#define WORDS_MISSEDMATCHFORMAT "%d mismatch in the sentence %d\n"  
#define WORDS_MISSEDMATCHSFORMAT "%d mismatches in the sentence %d\n"  
#define WORDS_MISSEDWORDFORMAT "for the word \"%s\" to translate as \"%s\""  
#define WORDS_MISSEDALTERNATEWORDFORMAT " or \"%s\""  
#define WORDS_NOTESFORMAT "notes from the glossary: %s"  
#define WORDS_DEFSCOUNTF "\nThere are %d definitions in the glossary."  
  
#define LABELS_REDEFINENAMEFROMSCRIPT "%s %d has already been named '%s' before, would you like to rename it as '%s'?"  
  
#define IMPORT_WOULDYOULIKEORIGINALSTRING "Do you want to Import the original sentences instead of the translations? "  
#define IMPORT_WOULDYOULIKELABELSEARCH "Import sentences by identifying through the labels rather than through the indexes?"  
  
#define WARNING_FUTUREBOXDATA "This file has been saved with a more recent version of TraduSCI, and it contains some additional data that will be kept unchanged. It is however recommended not to modify this file using a version of SCIaMano older than 1.2, or the aforesaid data will be lost."  
  
