
#define INTERFACE_OPENAUDRESFILTER "Archivos de Audio (*.AUD)\0*.aud\0\0"  
#define INTERFACE_OPENMAPFILTER "Archivos de MAPeado (*.map)\0*.map\0Volúmenes de MAPeado (*.map)\0*.map\0\0"  
#define INTERFACE_SAVEMAPFILTER "Archivos de MAPeado de Audio (*.map)\0*.map\0\0"  
#define INTERFACE_OPENFILEFILTER "Archivos de Mensaje (*.msg)\0*.msg\0Todos los Archivos (*.*)\0*.*\0\0"  
#define INTERFACE_SAVEFILEFILTER "Archivos de Mensaje de Sierra (*.msg)\0*.msg\0Archivos de Mensaje TraduSCI2 (*.msg)\0*.msg\0\0"  
#define INTERFACE_SAVEMSGFILEFILTER "Archivos de Mensaje (*.msg)\0*.msg\0\0"  
#define INTERFACE_EXPORTTEXTFILTER "Archivos de Texto (*.txt)\0*.txt\0Todos los Archivos (*.*)\0*.*\0\0"  
#define INTERFACE_LOADHEAPFILEFILTER "Archivos de Scripts Dinámicos (*.hep)\0*.hep\0Archivos de Volumen de MAPeado (*.map)\0*.map\0\0"  
#define INTERFACE_GOBUTTON "Ir a..."  
#define INTERFACE_FINDBUTTON "Buscar"  
#define INTERFACE_REPLACEBUTTON "Reemplazar"  
#define INTERFACE_CASESENSITIVE "con ABC =/= abc"  
#define INTERFACE_ORIGINALBUTTON "Mensajes"  
#define INTERFACE_TRANSLATIONBUTTON "Traducciones"  
#define INTERFACE_ORIGINAL "M\nE\nS\nS"  
#define INTERFACE_TRANSLATION "T\nR\nA\nN"  
#define INTERFACE_COMMENTS "N\nO\nT\nE"  
#define INTERFACE_ITEMCOUNT " frases"  
#define INTERFACE_NOFILELOADED "No hay un archivo de Mensaje cargado"  
#define INTERFACE_FILECOMPARETITLE "Elige un archivo para comparar"  
#define INTERFACE_SEARCHTITLE "Resultados de la búsqueda"  
#define INTERFACE_ENDOFFILESSTR "La búsqueda se vuelve al primer archivo desde el que empezaste."
#define INTERFACE_INVALIDSEARCHHANDLE "La búsqueda no puede continuar, el archivo puede haber sido movido o eliminado."  
#define INTERFACE_SELECTOP "Elige una acción: "  
#define INTERFACE_LABEL "Etiqueta"  
#define INTERFACE_CLONEOF "Clon de"  
#define INTERFACE_SEARCH "en"  
#define INTERFACE_INDEX "Índice"  
#define INTERFACE_NOUN "Nombre"  
#define INTERFACE_VERB "Verbo"  
#define INTERFACE_CASE "Evento"  
#define INTERFACE_SEQUENCE "Secuencia"  
#define INTERFACE_TALKER "Conversador"  
#define INTERFACE_MESSAGE "Mensaje"  
#define INTERFACE_MTRANSLATION "Traducción"  
#define INTERFACE_COMMENT "Notas"  
#define INTERFACE_UNCLONINGTITLE "Clonando"  
#define INTERFACE_PROPERTIESTITLE "Propiedades"  
#define INTERFACE_PROPERTIESFORMATSTRING "\nSCI Versión: %s                   \nFormato de Archivo: %s\nFrases: %d\nValor desconocido: %d\nNotas: %s\nArchivo de MAPeado: %s\n"  
#define INTERFACE_GENERICLABEL "<genérico>"  
#define INTERFACE_GENERICFLABEL "<genérico>"  
  
#define BUTTON_NEXTFILE "Archivo siguiente"  
#define BUTTON_STOPSEARCH "Detener"  
#define BUTTON_FIRSTSTRING "Primera frase"  
  
#define BUTTON_CANCEL "Cancelar"  
#define BUTTON_SELECTAUDMAP "Modificar .MAP"  
#define BUTTON_JUSTUNCLONE "Sólo Desclonar"  
  
#define BUTTON_CLOSE "Cerrar"  
#define BUTTON_LOADMSG "Abrir .MSG"  
#define BUTTON_LOADRES "Abrir Volumen"  
#define BUTTON_MANUAL "Manual"  
  
#define EXPORT_INFO "\n\n--Atención: La primera parte de este archivo enumera las frases traducidas para usar el corrector Ortográfico. Si una pulsación del ENTER es añadida en esa sección, será insertado en las frases. Además, no modifiques los números que identifican las frases. \nLos datos que empiezan desde este punto no son detectables y pueden ser eliminados si no son necesarios.--\n\n\n"  
#define EXPORT_ITEM "Frase %u:\n%s\n\n"  
#define EXPORT_ENDSECTION "\n\n---- Fin de la sección ----\n"  
#define EXPORT_COPYRIGHT "Este archivo ha sido producido por SCIaMano 1.4.0 de Enrico Rolfi.\n\n\n"  
#define EXPORT_FILEPATH "Ruta: %s\n"  
#define EXPORT_FORMAT "Formato: %s\n"  
#define EXPORT_VERSION "Versión: %s\n"  
#define EXPORT_ITEMCOUNT "Número de frases: %u\n"  
#define EXPORT_COMMENTS "Comentarios disponibles: %s\n"  
#define EXPORT_YES "Sí"  
#define EXPORT_NO "No"  
#define EXPORT_ITEM2 "- Frase %u - \n%s\n\n"  
#define EXPORT_TRANSLATION "- Traducción - \n%s\n\n"  
#define EXPORT_COMMENTITEM " - Nota - \n%s\n\n"  
#define EXPORT_ENDOFFILE "\n\n---- Fin del archivo ----\n\n"  
  
#define EXPORT_DIFFTITLE "Diferencias entre el archivo actual y el segundo archivo\n\nArchivo 1 - %s\nArchivo 2 - %s\n\n"  
#define EXPORT_MAPTITLE "¡El listado de frases no se encuentra en el MAPeado (MAP) elegido!\n\n"  
  
#define IMPORT_CANTFINDLABEL "No se puede encontrar la frase %s en el archivo de texto, porque hay %s en su lugar."  
  
#define ERR_TITLE "Error"  
#define ERR_CANTLOADFILE "No se pudo cargar el archivo debido a un error."  
#define ERR_FILEMOVED "El archivo no existe, o ha sido movido o eliminado."  
#define ERR_CANTSAVECHANGES "No se pueden guardar los cambios en el archivo. Por favor, intentar guardar en un nuevo archivo."  
#define ERR_CANTSAVE "No se puede guardar en el nuevo archivo debido a un error."  
#define ERR_CANTEXPORTTEXT "No se pueden exportar las frases debido a un error."  
#define ERR_NEWERFILEVERSION "Este archivo ha sido creado con una versión más reciente de SCIaMano y no puede ser usado."  
#define ERR_STRITEM1 "Un problema de memoria ha ocurrido en strItem->setString(tempStr) del formato de Sierra."  
#define ERR_STRITEM2 "Un problema de memoria ha ocurrido en strItem->setString(tempStr2) del formato de TraduSCI."  
#define ERR_STRITEM3 "Un problema de memoria ha ocurrido en strItem->setTranString(tempStr) del formato de TraduSCI."  
#define ERR_STRITEM4 "Un problema de memoria ha ocurrido en strItem->setString(tempStr) del formato de TraduSCI."  
#define ERR_COMITEM "Un problema de memoria ha ocurrido en comItem->setString(tempStr). "  
#define ERR_UNKNOWNGAME "El archivo elegido parece pertenecer a un juego que no reconozco. Por favor, contacta conmigo para así poder darle soporte. (VersionTag = 0x%X) "  
#define ERR_MESSAGEFROMAUTHOR "Mensaje de Enrico Rolfi (Endroz) "  
#define ERR_FIELD1 "No se puede crear el campo de las frases."  
#define ERR_FIELD2 "No se puede crear el campo de las traducciones."  
#define ERR_FIELD3 "No se puede crear el campo de los comentarios."  
#define ERR_FIELD4 "No se puede crear el campo del Índice."  
#define ERR_FIELD5 "No se puede crear el campo de Búsqueda."  
#define ERR_FIELD6 "No se puede crear el campo de Reemplazar."  
#define ERR_DIFFIMPFILE "El archivo elegido tiene un número diferente de frases y no puede ser Importado."  
#define ERR_DIFFCMPFILE "El archivo elegido tiene un número diferente de frases y no puede ser Comparado."  
#define ERR_CANTCMPSAMEFILE "¡El archivo elegido es el mismo que estás intentado comparar!"  
#define ERR_CANTALLOCSTRING "Ha ocurrido un problema de memoria. La frase traducida no ha sido grabada."  
#define ERR_CANTLOADHEAPFILE "¡Error al cargar el archivo de Script Dinámico (Heap)!"  
#define ERR_CANTLOADDLL "¡No se puede cargar SCIdump.dll! Este programa fallará si intentas cargar un archivo de Volumen."

#define ERR_CANTGGTRANSLATE "No puedo traducir una frase que sea clon de otra. Traduzca la frase original o elimine la clonación primero."

#define WARN_ATTENTION "¡Atención!"  
#define WARN_SIERRAFORMAT "El archivo está en el formato de Sierra, así que sólo puedes guardar las frases traducidas en el lugar de las originales. Además no habrá soporte para los datos especiales de TraduSCI (como el MAPeado (MAP) y las etiquetas) \n¿Quieres convertirlo en el formato de TraduSCI para mantener ambas versiones en las frases (y los datos especiales)?"  
#define WARN_OLDFORMAT "Este archivo está en un formato antiguo de TraduSCI, y al grabar los cambios automáticamente lo convertirás en el formato TraduSCI2 y no serás capaz de usar el archivo en versiones anteriores del programa. ¿Continuar de todos modos? "  
#define WARN_UNSAVEDCHANGES "Tus cambios en el archivo actual no han sido guardados. ¿Quieres guardar antes de abrir otro archivo? "  
#define WARN_QUITONUNSAVED "Tus cambios en el archivo actual no han sido guardados. ¿Quieres guardar antes de cerrar SCIaMano? "  
  
#define WARN_TEMPORARYFILEEXISTS "Un archivo temporal de una sesión anterior (o de una sesión aún en progreso) ha sido encontrado. ¿Quieres cargar este archivo temporal?"    
  
#define WARN_ENDOFFILEDURINGSEARCH "Fin del archivo. \n\nPuedes empezar desde la primera frase o continuar hacia el siguiente archivo."  
  
#define WARN_ENDTAGNAMESNOTFOUND "Hay un problema con este archivo. ¡El final del bloque de etiquetas no ha sido reconocido! Procede con precaución."  
#define WARN_ENDTAGMAPSNOTFOUND "Hay un problema con este archivo. ¡El final del bloque del MAPeado de Audio no ha sido reconocido! Procede con precaución."  
  

#define MENU_MESSAGE "&Mensajes"  
#define MENU_LOAD "&Abrir... \tCtrl+A"  
#define MENU_OPENVOL "&Cargar desde el Volumen... "  
#define MENU_SAVE "&Guardar\tCtrl+G"  
#define MENU_SAVEAS "G&uardar cómo... "  
  
#define MENU_IMPORT "&Importar desde un archivo de texto... "  
#define MENU_EXPORT "&Exportar a un archivo de texto... "  
#define MENU_ABOUT "Acerca de... "  
#define MENU_QUIT "&Salir\tCtrl+S"  
#define MENU_PROPERTIES "&Propiedades... "    
#define MENU_CLONE "Clonando la frase actual... "  
  
#define MENU_NOUNSHEAP "Importar nombres desde el Script Dinámico (Heap)... "  
#define MENU_LOADLABELSTXT "Importar desde un archivo de texto... "  
#define MENU_EXPORTLABELSTOTXT "Exportar desde un archivo de texto... "  
  
#define MENU_LABELS "Etiquetas"  
  
#define MENU_STRING "&Frases"  
#define MENU_FIRST "P&rimera\tCtrl+Inicio"  
#define MENU_PREVIOUS "A&nterior\tCtrl+Cursor Arriba"  
#define MENU_NEXT "Si&guiente\tCtrl+Cursor Abajo"  
#define MENU_LAST "Ú&ltima\tCtrl+Fin"  
#define MENU_ENTER "&Ir a...\tCtrl+Enter"  
  
#define MENU_FIND "&Buscar\tCtrl+B"  
#define MENU_REPLACE "&Reemplazar\tCtrl+R"  
#define MENU_IMPORTFILE "I&mportar desde un Mensaje... "  
#define MENU_COMPAREFILE "C&omparar con un Mensaje... "  
  
  
#define MENU_SHOWUNKBYTES "&Mostrar datos especiales"  
  
#define MENU_WORDL "Glosario"  
#define MENU_ADDTOWL "Añadir a la selección\tCtrl+I"  
#define MENU_DOWORDSLOOKUP "Comprobar palabras\tCtrl+K"  
#define MENU_SHOWWL "Mostrar glosario"  
  
#define MENU_FONT "&Tamaño de la fuente"  
#define MENU_FONT14 "14"  
#define MENU_FONT16 "16"  
#define MENU_FONT18 "18"  
#define MENU_FONT20 "20"  
#define MENU_FONT22 "22"  
#define MENU_FONT24 "24"  
#define MENU_FONT26 "26"  
  
#define MENU_NAVIGATION "&Navegación"  
  
  
#define MENU_GRAPH "Diagrama"  
#define MENU_DRAWGF "Dibujar diagrama\tCtrl+G"  
#define MENU_DRAWGFBW "Dibujar diagrama sin colores"  
  
#define MENU_OTHERGRAPH "... con diferente clasificación"  
#define MENU_DRAWNOUNGF "Diagrama de Nombres"  
#define MENU_DRAWCASEGF "Diagrama de Eventos"  
#define MENU_DRAWVERBGF "Diagrama de Verbos"  
#define MENU_DRAWTALKERGF "Diagrama de Conversadores"  
#define MENU_DRAWINDEXGF "Diagrama de Índices"  
  
#define MENU_AUDIO "Audio"  
#define MENU_LOADMAP "Cargar MAPeado (MAP)... "  
#define MENU_EXPORTMAP "Exportar MAPeado actual... "  
#define MENU_VERIFYMAP "Verificar Mensajes en el MAPeado... "  
  
#define MENU_PLAY "Reproducir frase actual"  
#define MENU_LOADAUDRES "Localizar 'RESOURCE.AUD'... "  
#define MENU_AUTOPLAY "Auto Reproducción"  
  
#define MENU_NEXTCOMMENT "Ir a la Nota siguiente\tCtrl+D"  
  
#define MENU_TRANSLATION "Traducción"
#define MENU_AUTOTRANSLATE "Iniciar traducción automática"
#define MENU_STOPTRANSLATE "Detener traducción automática"
#define MENU_SINGLETRANSLATE "Traducir la frase actual"
#define MENU_SOURCELANGUAGE "Idioma original"
#define MENU_TRANSLANGUAGE "Idioma de traducción"

#define MENU_HELP "Manual de TraduSCI... "   
    
#define WIN_FILEDESCRIPTION "Programa para traducir juegos SCI1.1/SCI32.\0"  
#define WIN_LEGALCOPYRIGHT "\251 Enrico Rolfi (Endroz), 2003-2021. Traducción al Español de SkaZZ.\0"  
#define WIN_LEGALTRADEMARKS "SCI (Sierra Creative Interpreter) es una marca registrada de Sierra On-Line que mantiene los derechos. \0"  
#define WIN_FILEVERSION "1.4.0\0"  
#define WIN_PRODUCTVERSION "2.4\0"  
#define WIN_FILEVERSIONID 1,4,0,0  
#define INTERFACE_ABOUTBOX "Este programa es de código abierto (Licencia GNU GPL) y puede ser libremente distribuido y modificado siempre y cuando permanezca como código abierto. El autor rechaza cualquier responsabilidad de los posibles daños causados por su uso. SCI es una marca registrada de Sierra On-Line."  
#define INTERFACE_ABOUTTITLE "\251 Enrico Rolfi (Endroz), 2003-2021. Traducción de SkaZZ.\n\nEn memoria de Michele Del Bene (Micartu)\n\nActualizaciones en http://erolfi.wordpress.com\n\nPara problemas, sugerencias y otros escribid a:\n erolfi en gmail.com\n\n"  
#define INTERFACE_VERSION "Versión 1.4.0"  
  
#define MANUAL_PATH "Manual\\instrucciones.html"  
          
  
#define GRAPH_CLONEOF "\\fn\nClon del Nombre%d, Verbo %d, Evento %d"  
#define GRAPH_NOUN "Nombre"  
#define GRAPH_VERB "Verbo"  
#define GRAPH_CASE "Evento"  
#define GRAPH_TALKER "Conversador"  
#define GRAPH_CANTCREATEFILE "No se puede crear el archivo del diagrama (¿quizás el disco está protegido?). "  
  
#define MAPS_REPLACEEXISTING "Este archivo de Mensaje ya tiene un MAPeado de Audio cargado, ¿seguro que quieres reemplazarlo?"  
#define MAPS_MAPFILENOTFOUND "Este archivo MSG necesita un archivo MAP válido para ser capaz de funcionar en el juego. ¿Quieres crearlo ahora (reemplazando cualquier archivo MAP con el mismo nombre en este mismo directorio)? "  
#define MAPS_WRONGENDOFMAPFILE "A este archivo MAP no se le reconoce el formato y además no es posible cargarlo. \n(el último elemento no es -1 como se esperaba) "  
#define MAPS_WRONGMAPFILESIZE "El tamaño del archivo MAP no es el correcto y además no es posible cargarlo."  
#define MAPS_STRANGESCIPATCHINMAPFILE "El archivo MAP no tiene un formato reconocible y además no es posible cargarlo. \n(no hay un indicador correcto en el SCI PATCH al principio del archivo) "  
#define MAPS_CANTACCESSMAPFILE "¡No es posible acceder al archivo MAP! "  
#define MAPS_ITEMALREADYEXISTS "¡No fue posible insentar el elemento en el archivo MAP! Un elemento ya existe con la misma etiqueta."  
#define MAPS_LISTERRORDURINGINSERT "¡No fue posible insentar el elemento en el archivo MAP!\n(error durante la insercción en la lista)"  
#define MAPS_CANTFINDORIGINALTOCOPYFROM "¡No fue posible insentar el elemento en el archivo MAP! La frase original la cual copia la referencia al audio no ha sido encontrada."  
#define MAPS_NOMAPINMEMORY "¡No hay en memoria una estructura MAP presenta a la cual aplicar los cambios!"  
#define MAPS_MAPCHECKFORMATSTRING "Índice: %d - Nombre: %d Verbo: %d Evento: %d Secuencia: %d%s\n"  
#define MAPS_BUTITISACLONE " (pero es un Clon)"  
#define MAPS_CANTFINDENTRY "¡La referencia al audio no ha sido encontrada en el MAP (podría ser un Clon)! "  
  
#define MAPS_WASNTREMOVEDMIGHTBEUSEFUL "La entrada en el MAPeado de Audio no ha sido eliminada porque se refiere a un archivo de sonido existente, que podría ser útil en el caso de que decidieras Desclonar este mensaje en el futuro."  
#define MAPS_ENTRYREMOVED "La entrada en el MAPeado de Audio ha sido corréctamente eliminada."  
#define MAPS_TITLE "MAPeado de Audio"  
  
#define MAPS_NOTLOADED "no cargado"  
  
#define AUDIO_CANTFINDRESAUD "¡No se puede encontrar el volumen RESOURCE.AUD! Por favor, cárgalo mediante la acción adecuada en su propio menú. Si ya lo has hecho, entonces por favor comprueba que el MAPeado no ha sido movido ni eliminado."  
#define AUDIO_NOTASOLFILE "El archivo RESOURCE.AUD o el MAPeado de Audio en uso podría estar corrompido. ¡La dirección actual en el MAPeado de Audio no hace referencia a ningún tipo de archivo de audio SOL!"  
#define AUDIO_MUSTLOADMAPFIRST "Para ser capaz de reproducir esta frase es necesario cargar el MAPeado de Audio de este archivo de Mensaje (por ejemplo: 100000.map. "  
   
#define CLONES_UNCLONEBTN "Desclonar"  
#define CLONES_CLONEBTN "Clonar"  
#define CLONES_SEQLABEL "SECUENCIA"  
#define CLONES_HIERARCHICAL "Por favor, recuerda que las frases pertenecientes a las listas u otros interfaces podrían ser útiles en los scripts, ¡y si la desclonas podrías no hacer funcionar el juego! (Nota: desclonar esta frase te dará otro clon, porque la frase original es un clon de ella misma; además sería necesario repetir la operación de desclonar para conseguir una frase modificable.) "   
#define CLONES_DUPLICATESEQ "¡Esta frase es un clon de la secuencia entera! ¿En vez de desclonar la frase (además de conseguir sólo una copia de la primera frase de la secuencia), te gustaría copiar esa secuencia, y conectar este clon a esta copia?"  
#define WARN_UNCLONINGAREYOUSURE "Por favor, recuerda que las frases pertenecientes a las listas u otros interfaces podrían ser útiles en los scripts, ¡y si la desclonas podrías no hacer funcionar el juego!\n\nCon voces, se requiere modificar el MAPeado del archivo de audio (.MAP) también. Puedes hacerlo pulsando el botón derecho aquí (lee el manual para más información sobre clones): "   
#define CLONES_CANTUNCLONESEQ "¡No se puede crear un duplicado de la frase clonada!"  
#define CLONES_UNCLONINGSUCCEDED "Acción de desclonar realizada."  
#define CLONES_CANTCLONESEQINTERMEDIATE "¡Una frase intermediaria de una secuencia no puede ser clonada!"  
#define CLONES_UNCLONEDSEQLABEL "DESCLONAR SECUENCIA"  
#define CLONES_LABELFORMAT "%sClon del Nombre %d, Verbo %d, Evento %d"  
#define CLONES_CLONINGENTERINDEX "¡Con este procedimiento, la frase actual será convertida en un clon!\n Introduce el Índice del primer mensaje de la secuencia de referencia de la cual crear el nuevo clon: "  
#define CLONES_CLONINGREMARK "Nota: si existe una referencia en el mensaje actual en el archivo MAP, el procedimiento de clonar no la eliminará (a menos que esto sea un mensaje anteriormente desclonado). Recuerda que, cuando se muestra un clon, el juego siempre usará el audio relacionado al mensaje original."  
#define CLONES_CANTCLONEWRONGINDEX "¡El Índice introducido no corresponde a ningún mensaje! "  
  
#define WORDS_WORDALREADYEXISTS "Esta palabra ya existe en el glosario. ¿Quieres añadir más a la definición? "  
#define WORDS_CANTACCESSWORDSFILE "No se puede abrir el glosario. Verifica que el archivo  \"wordlookup.txt\" está localizado en el mismo directorio que el archivo MSG abierto actualmente."  
#define WORDS_NOSELECTIONTOADD "¡No hay ninguna selección para añadir al glosario!"  
#define WORDS_CANTCREATEREPORT "¡No se puede crear el archivo que contiene el informe! "  
  
#define WORDS_WFHEADERROW1 "# Archivo de glosario para los términos comunes en el MSG\n#\n"  
#define WORDS_WFHEADERROW2 "# Síntaxis de cada línea del archivo que ha estado como:\n#    <palabra original> = <traducción1> | <traducción2> |... \n#\n"  
#define WORDS_WFHEADERROW3 "# Palabras que pueden contener espacios intermedios, y así\n#  puedes también guardar traduciones de frases enteras\n"  
#define WORDS_WFHEADERROW4 "# Para insertar comentarios, usa el carácter # \n"  
  
#define WORDS_MISSEDMATCHFORMAT "%d no coincide en la frase %d\n"  
#define WORDS_MISSEDMATCHSFORMAT "%d no coincidencias en la frase %d\n"  
#define WORDS_MISSEDWORDFORMAT "para la palabra \"%s\" traducir como \"%s\""  
#define WORDS_MISSEDALTERNATEWORDFORMAT " o \"%s\""  
#define WORDS_NOTESFORMAT "notas del glosario: %s"  
#define WORDS_DEFSCOUNTF "\nHay %d definiciones en el glosario."  
  
#define LABELS_REDEFINENAMEFROMSCRIPT "%s %d ya ha sido llamado '%s' antes, ¿te gustaría renombrarlo como '%s'?"  
  
#define IMPORT_WOULDYOULIKEORIGINALSTRING "¿Quieres Importar las frases originales en vez de las traduciones? "  
#define IMPORT_WOULDYOULIKELABELSEARCH "¿Importar frases para identificar a través de las etiquetas en vez de los índices?"  
  
#define WARNING_FUTUREBOXDATA "Este archivo ha sido guardado con una versión más reciente de TraduSCI, y contiene algunos datos adicionales que se mantendrán sin cambios. Sin embargo, es recomendado no modificar este archivo usando una versión de SCIaMano más antigua que la 1.2, o los datos mencionados antes se perderán."  
  
#define WARNING_GGTRANSEXISTS "Esta frase ya tiene traducción, ¿estás seguro de que quieres sobrescribirla?"
